# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_numpy1.20openssl1.1.1python3.8.____cpython:
        CONFIG: linux_64_numpy1.20openssl1.1.1python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_numpy1.20openssl1.1.1pytho_h56700011c9
      linux_64_numpy1.20openssl1.1.1python3.9.____cpython:
        CONFIG: linux_64_numpy1.20openssl1.1.1python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_numpy1.20openssl1.1.1pytho_h90f93beee8
      linux_64_numpy1.20openssl3python3.8.____cpython:
        CONFIG: linux_64_numpy1.20openssl3python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_numpy1.20openssl3python3.8.____cpython
      linux_64_numpy1.20openssl3python3.9.____cpython:
        CONFIG: linux_64_numpy1.20openssl3python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_numpy1.20openssl3python3.9.____cpython
      linux_64_numpy1.21openssl1.1.1python3.10.____cpython:
        CONFIG: linux_64_numpy1.21openssl1.1.1python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_numpy1.21openssl1.1.1pytho_h9d29ba6ef8
      linux_64_numpy1.21openssl3python3.10.____cpython:
        CONFIG: linux_64_numpy1.21openssl3python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_numpy1.21openssl3python3.10.____cpython
      linux_64_numpy1.23openssl1.1.1python3.11.____cpython:
        CONFIG: linux_64_numpy1.23openssl1.1.1python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_numpy1.23openssl1.1.1pytho_hb1b66b3008
      linux_64_numpy1.23openssl3python3.11.____cpython:
        CONFIG: linux_64_numpy1.23openssl3python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_64_numpy1.23openssl3python3.11.____cpython
      linux_aarch64_numpy1.20openssl1.1.1python3.8.____cpython:
        CONFIG: linux_aarch64_numpy1.20openssl1.1.1python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_numpy1.20openssl1.1.1_h84c80dee64
      linux_aarch64_numpy1.20openssl1.1.1python3.9.____cpython:
        CONFIG: linux_aarch64_numpy1.20openssl1.1.1python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_numpy1.20openssl1.1.1_h49d3bb948f
      linux_aarch64_numpy1.20openssl3python3.8.____cpython:
        CONFIG: linux_aarch64_numpy1.20openssl3python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_numpy1.20openssl3pyth_h7745bd5b27
      linux_aarch64_numpy1.20openssl3python3.9.____cpython:
        CONFIG: linux_aarch64_numpy1.20openssl3python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_numpy1.20openssl3pyth_hf4106c6d68
      linux_aarch64_numpy1.21openssl1.1.1python3.10.____cpython:
        CONFIG: linux_aarch64_numpy1.21openssl1.1.1python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_numpy1.21openssl1.1.1_ha7ab4b30ed
      linux_aarch64_numpy1.21openssl3python3.10.____cpython:
        CONFIG: linux_aarch64_numpy1.21openssl3python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_numpy1.21openssl3pyth_h9360ca082d
      linux_aarch64_numpy1.23openssl1.1.1python3.11.____cpython:
        CONFIG: linux_aarch64_numpy1.23openssl1.1.1python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_numpy1.23openssl1.1.1_he223b53bb7
      linux_aarch64_numpy1.23openssl3python3.11.____cpython:
        CONFIG: linux_aarch64_numpy1.23openssl3python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_aarch64_numpy1.23openssl3pyth_h72c8e9e6b0
      linux_ppc64le_numpy1.20openssl1.1.1python3.8.____cpython:
        CONFIG: linux_ppc64le_numpy1.20openssl1.1.1python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_numpy1.20openssl1.1.1_he37e51b2be
      linux_ppc64le_numpy1.20openssl1.1.1python3.9.____cpython:
        CONFIG: linux_ppc64le_numpy1.20openssl1.1.1python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_numpy1.20openssl1.1.1_h577859b0e0
      linux_ppc64le_numpy1.20openssl3python3.8.____cpython:
        CONFIG: linux_ppc64le_numpy1.20openssl3python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_numpy1.20openssl3pyth_hce2c7da967
      linux_ppc64le_numpy1.20openssl3python3.9.____cpython:
        CONFIG: linux_ppc64le_numpy1.20openssl3python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_numpy1.20openssl3pyth_h8677f5c0ab
      linux_ppc64le_numpy1.21openssl1.1.1python3.10.____cpython:
        CONFIG: linux_ppc64le_numpy1.21openssl1.1.1python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_numpy1.21openssl1.1.1_h658d828d2f
      linux_ppc64le_numpy1.21openssl3python3.10.____cpython:
        CONFIG: linux_ppc64le_numpy1.21openssl3python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_numpy1.21openssl3pyth_h702d2472cc
      linux_ppc64le_numpy1.23openssl1.1.1python3.11.____cpython:
        CONFIG: linux_ppc64le_numpy1.23openssl1.1.1python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_numpy1.23openssl1.1.1_heeda7f68bb
      linux_ppc64le_numpy1.23openssl3python3.11.____cpython:
        CONFIG: linux_ppc64le_numpy1.23openssl3python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
        SHORT_CONFIG: linux_ppc64le_numpy1.23openssl3pyth_hf1c296b381
  timeoutInMinutes: 360

  steps:
  - script: |
         rm -rf /opt/ghc
         df -h
    displayName: Manage disk space

  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
  - script: |
        export CI=azure
        export CI_RUN_ID=$(build.BuildNumber).$(system.JobAttempt)
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        export CONDA_BLD_DIR=build_artifacts
        export ARTIFACT_STAGING_DIR="$(Build.ArtifactStagingDirectory)"
        # Archive everything in CONDA_BLD_DIR except environments
        export BLD_ARTIFACT_PREFIX=conda_artifacts
        if [[ "$AGENT_JOBSTATUS" == "Failed" ]]; then
          # Archive the CONDA_BLD_DIR environments only when the job fails
          export ENV_ARTIFACT_PREFIX=conda_envs
        fi
        ./.scripts/create_conda_build_artifacts.sh
    displayName: Prepare conda build artifacts
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    displayName: Store conda build artifacts
    condition: not(eq(variables.BLD_ARTIFACT_PATH, ''))
    inputs:
      targetPath: $(BLD_ARTIFACT_PATH)
      artifactName: $(BLD_ARTIFACT_NAME)

  - task: PublishPipelineArtifact@1
    displayName: Store conda build environment artifacts
    condition: not(eq(variables.ENV_ARTIFACT_PATH, ''))
    inputs:
      targetPath: $(ENV_ARTIFACT_PATH)
      artifactName: $(ENV_ARTIFACT_NAME)